// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"database/sql"
	"time"
)

type Action struct {
	ID                 int64
	SessionID          int64
	ActorName          sql.NullString
	FeatureName        sql.NullString
	Trigger            sql.NullString
	Intent             sql.NullString
	StructuredJsonData sql.NullString
	RpcMethod          string
	RpcParamsJson      []byte
	CreatedAt          time.Time
	ActionState        int16
	ErrorReason        sql.NullString
}

type FeatureConfig struct {
	SessionID   int64
	FeatureName string
	Config      []byte
}

type MacaroonCaveat struct {
	SessionID      int64
	ID             []byte
	VerificationID []byte
	Location       sql.NullString
}

type MacaroonPermission struct {
	SessionID int64
	Entity    string
	Action    string
}

type PrivacyFlag struct {
	SessionID int64
	Flag      int32
}

type Session struct {
	ID              int64
	LegacyID        []byte
	Label           string
	SessionState    int16
	SessionType     int16
	Expiry          time.Time
	CreatedAt       time.Time
	RevokedAt       sql.NullTime
	ServerAddress   string
	DevServer       bool
	MacaroonRootKey int64
	PairingSecret   []byte
	LocalPrivateKey []byte
	LocalPublicKey  []byte
	RemotePublicKey []byte
	Privacy         bool
	GroupID         sql.NullInt64
}
