// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountActions(ctx context.Context, arg CountActionsParams) (int64, error)
	GetAllPrivacyPairs(ctx context.Context, groupID int64) ([]GetAllPrivacyPairsRow, error)
	GetLegacyIDBySessionID(ctx context.Context, id int64) ([]byte, error)
	GetPseudoForReal(ctx context.Context, arg GetPseudoForRealParams) (string, error)
	GetRealForPseudo(ctx context.Context, arg GetRealForPseudoParams) (string, error)
	GetSessionByID(ctx context.Context, id int64) (Session, error)
	GetSessionByLegacyID(ctx context.Context, legacyID []byte) (Session, error)
	GetSessionByLocalPublicKey(ctx context.Context, localPublicKey []byte) (Session, error)
	GetSessionFeatureConfigs(ctx context.Context, sessionID int64) ([]FeatureConfig, error)
	GetSessionIDByLegacyID(ctx context.Context, legacyID []byte) (int64, error)
	GetSessionLegacyIDsInGroup(ctx context.Context, groupID sql.NullInt64) ([][]byte, error)
	GetSessionMacaroonCaveats(ctx context.Context, sessionID int64) ([]MacaroonCaveat, error)
	GetSessionMacaroonPermissions(ctx context.Context, sessionID int64) ([]MacaroonPermission, error)
	GetSessionPrivacyFlags(ctx context.Context, sessionID int64) ([]PrivacyFlag, error)
	GetSessionsInGroup(ctx context.Context, groupID sql.NullInt64) ([]Session, error)
	InsertAction(ctx context.Context, arg InsertActionParams) (int64, error)
	InsertFeatureConfig(ctx context.Context, arg InsertFeatureConfigParams) error
	InsertMacaroonCaveat(ctx context.Context, arg InsertMacaroonCaveatParams) error
	InsertMacaroonPermission(ctx context.Context, arg InsertMacaroonPermissionParams) error
	InsertPrivacyFlag(ctx context.Context, arg InsertPrivacyFlagParams) error
	InsertPrivacyPair(ctx context.Context, arg InsertPrivacyPairParams) error
	InsertSession(ctx context.Context, arg InsertSessionParams) (int64, error)
	ListActions(ctx context.Context, arg ListActionsParams) ([]Action, error)
	ListActionsPaginated(ctx context.Context, arg ListActionsPaginatedParams) ([]Action, error)
	ListSessions(ctx context.Context) ([]Session, error)
	ListSessionsByType(ctx context.Context, type_ int16) ([]Session, error)
	SetActionState(ctx context.Context, arg SetActionStateParams) error
	SetRemotePublicKeyByLocalPublicKey(ctx context.Context, arg SetRemotePublicKeyByLocalPublicKeyParams) error
	SetSessionGroupID(ctx context.Context, arg SetSessionGroupIDParams) error
	UpdateSessionState(ctx context.Context, arg UpdateSessionStateParams) error
}

var _ Querier = (*Queries)(nil)
