// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: lit-status.proto

package litrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSubServerStateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The name of the sub-server for which the status is to be queried for.
	SubServerName string `protobuf:"bytes,1,opt,name=sub_server_name,json=subServerName,proto3" json:"sub_server_name,omitempty"`
}

func (x *GetSubServerStateReq) Reset() {
	*x = GetSubServerStateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lit_status_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSubServerStateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubServerStateReq) ProtoMessage() {}

func (x *GetSubServerStateReq) ProtoReflect() protoreflect.Message {
	mi := &file_lit_status_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubServerStateReq.ProtoReflect.Descriptor instead.
func (*GetSubServerStateReq) Descriptor() ([]byte, []int) {
	return file_lit_status_proto_rawDescGZIP(), []int{0}
}

func (x *GetSubServerStateReq) GetSubServerName() string {
	if x != nil {
		return x.SubServerName
	}
	return ""
}

type GetSubServerStateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// running is true if the sub-server is currently running.
	Running bool `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	// error describes an error that might have resulted in the sub-server not
	// starting up properly.
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetSubServerStateResp) Reset() {
	*x = GetSubServerStateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lit_status_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSubServerStateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubServerStateResp) ProtoMessage() {}

func (x *GetSubServerStateResp) ProtoReflect() protoreflect.Message {
	mi := &file_lit_status_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubServerStateResp.ProtoReflect.Descriptor instead.
func (*GetSubServerStateResp) Descriptor() ([]byte, []int) {
	return file_lit_status_proto_rawDescGZIP(), []int{1}
}

func (x *GetSubServerStateResp) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *GetSubServerStateResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_lit_status_proto protoreflect.FileDescriptor

var file_lit_status_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6c, 0x69, 0x74, 0x2d, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x6c, 0x69, 0x74, 0x72, 0x70, 0x63, 0x22, 0x3e, 0x0a, 0x14, 0x47, 0x65,
	0x74, 0x53, 0x75, 0x62, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x12, 0x26, 0x0a, 0x0f, 0x73, 0x75, 0x62, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x75, 0x62,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x47, 0x0a, 0x15, 0x47, 0x65,
	0x74, 0x53, 0x75, 0x62, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x32, 0x5a, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x50, 0x0a,
	0x11, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x1c, 0x2e, 0x6c, 0x69, 0x74, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x53,
	0x75, 0x62, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x1a, 0x1d, 0x2e, 0x6c, 0x69, 0x74, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x42,
	0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x69,
	0x67, 0x68, 0x74, 0x6e, 0x69, 0x6e, 0x67, 0x6c, 0x61, 0x62, 0x73, 0x2f, 0x6c, 0x69, 0x67, 0x68,
	0x74, 0x6e, 0x69, 0x6e, 0x67, 0x2d, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x2f, 0x6c,
	0x69, 0x74, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lit_status_proto_rawDescOnce sync.Once
	file_lit_status_proto_rawDescData = file_lit_status_proto_rawDesc
)

func file_lit_status_proto_rawDescGZIP() []byte {
	file_lit_status_proto_rawDescOnce.Do(func() {
		file_lit_status_proto_rawDescData = protoimpl.X.CompressGZIP(file_lit_status_proto_rawDescData)
	})
	return file_lit_status_proto_rawDescData
}

var file_lit_status_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_lit_status_proto_goTypes = []interface{}{
	(*GetSubServerStateReq)(nil),  // 0: litrpc.GetSubServerStateReq
	(*GetSubServerStateResp)(nil), // 1: litrpc.GetSubServerStateResp
}
var file_lit_status_proto_depIdxs = []int32{
	0, // 0: litrpc.Status.GetSubServerState:input_type -> litrpc.GetSubServerStateReq
	1, // 1: litrpc.Status.GetSubServerState:output_type -> litrpc.GetSubServerStateResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lit_status_proto_init() }
func file_lit_status_proto_init() {
	if File_lit_status_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lit_status_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSubServerStateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lit_status_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSubServerStateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lit_status_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lit_status_proto_goTypes,
		DependencyIndexes: file_lit_status_proto_depIdxs,
		MessageInfos:      file_lit_status_proto_msgTypes,
	}.Build()
	File_lit_status_proto = out.File
	file_lit_status_proto_rawDesc = nil
	file_lit_status_proto_goTypes = nil
	file_lit_status_proto_depIdxs = nil
}
